# Generated by Django 3.2.7 on 2021-12-08 03:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20211207_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRecipe',
            new_name='Favorite',
        ),
    ]
