# Generated by Django 3.2.7 on 2021-11-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_follow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'ингридиенты для рецепта', 'verbose_name_plural': 'ингридиенты для рецепта'},
        ),
    ]
