# Generated by Django 3.2.7 on 2021-12-09 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20211207_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_in_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorited',
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_add_to_cart',
            field=models.ManyToManyField(related_name='recipes_in_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_add_to_favorite',
            field=models.ManyToManyField(related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
