# Generated by Django 3.2.7 on 2021-11-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_favoriterecipe_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-name'], 'verbose_name': 'ингридиент', 'verbose_name_plural': 'ингридиенты'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='count',
        ),
    ]
