# Generated by Django 3.2.7 on 2021-12-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20211210_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'ингридиент', 'verbose_name_plural': 'ингридиенты'},
        ),
    ]
