# Generated by Django 3.2.7 on 2021-12-24 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0014_auto_20211223_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='users_in_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_in_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_in_shopping_cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_in_shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
